//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSnap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProSnap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap at_32x32 {
            get {
                object obj = ResourceManager.GetObject("at_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backward_18x32_backward {
            get {
                object obj = ResourceManager.GetObject("backward_18x32_backward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backward_18x32_white {
            get {
                object obj = ResourceManager.GetObject("backward_18x32_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backward_empty_18x32_black {
            get {
                object obj = ResourceManager.GetObject("backward_empty_18x32_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backward_empty_18x32_white {
            get {
                object obj = ResourceManager.GetObject("backward_empty_18x32_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Camera {
            get {
                object obj = ResourceManager.GetObject("Camera", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon camera_16x16_flash_large_icon {
            get {
                object obj = ResourceManager.GetObject("camera_16x16_flash_large_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon camera_16x16_flash_small_icon {
            get {
                object obj = ResourceManager.GetObject("camera_16x16_flash_small_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon camera_16x16_icon {
            get {
                object obj = ResourceManager.GetObject("camera_16x16_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera_36x36 {
            get {
                object obj = ResourceManager.GetObject("camera_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon camera_36x36_icon {
            get {
                object obj = ResourceManager.GetObject("camera_36x36_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_36x36 {
            get {
                object obj = ResourceManager.GetObject("chart_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap check_32x26 {
            get {
                object obj = ResourceManager.GetObject("check_32x26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cloud_upload_32x32_black {
            get {
                object obj = ResourceManager.GetObject("cloud_upload_32x32_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cloud_upload_32x32_white {
            get {
                object obj = ResourceManager.GetObject("cloud_upload_32x32_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cloud_upload_link_black_32x32 {
            get {
                object obj = ResourceManager.GetObject("cloud_upload_link_black_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cloud_upload_link_white_32x32 {
            get {
                object obj = ResourceManager.GetObject("cloud_upload_link_white_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cog_alt_32x32 {
            get {
                object obj = ResourceManager.GetObject("cog_alt_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_stroke_32x32_black {
            get {
                object obj = ResourceManager.GetObject("document_stroke_32x32_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_stroke_32x32_white {
            get {
                object obj = ResourceManager.GetObject("document_stroke_32x32_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream FlashBulb {
            get {
                return ResourceManager.GetStream("FlashBulb", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap forward_18x32_black {
            get {
                object obj = ResourceManager.GetObject("forward_18x32_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forward_18x32_white {
            get {
                object obj = ResourceManager.GetObject("forward_18x32_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forward_empty_18x32_black {
            get {
                object obj = ResourceManager.GetObject("forward_empty_18x32_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forward_empty_18x32_white {
            get {
                object obj = ResourceManager.GetObject("forward_empty_18x32_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap heart_fill_12x11 {
            get {
                object obj = ResourceManager.GetObject("heart_fill_12x11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap heart_fill_black_32x38 {
            get {
                object obj = ResourceManager.GetObject("heart_fill_black_32x38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap heart_fill_white_32x38 {
            get {
                object obj = ResourceManager.GetObject("heart_fill_white_32x38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap heart_stroke_black_32x28 {
            get {
                object obj = ResourceManager.GetObject("heart_stroke_black_32x28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap heart_stroke_white_32x28 {
            get {
                object obj = ResourceManager.GetObject("heart_stroke_white_32x28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_32x32_black {
            get {
                object obj = ResourceManager.GetObject("image_32x32_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_32x32_white {
            get {
                object obj = ResourceManager.GetObject("image_32x32_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pen_32x32_black {
            get {
                object obj = ResourceManager.GetObject("pen_32x32_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pen_32x32_white {
            get {
                object obj = ResourceManager.GetObject("pen_32x32_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpArrow_48x48 {
            get {
                object obj = ResourceManager.GetObject("UpArrow_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap works_on_my_machine_starburst {
            get {
                object obj = ResourceManager.GetObject("works_on_my_machine_starburst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x_28x28_black {
            get {
                object obj = ResourceManager.GetObject("x_28x28_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x_28x28_red {
            get {
                object obj = ResourceManager.GetObject("x_28x28_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x_28x28_white {
            get {
                object obj = ResourceManager.GetObject("x_28x28_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
